### ISSUE TITLE
JsonUtils.Enquote bugged

### ISSUE THREAD

**Issue by serprex** [extnet/Utilities#1]
https://github.com/extnet/Utilities/blob/master/Ext.Net.Utilities/JavaScript/JsonUtils.cs#L64

\u is suppose to be hex escaped. Are Bjolseth's code is incorrect

Corrected code @ https://github.com/Tolriq/Yatse2/blob/master/Yatse2/Plugins/Jayrock.Json/Json/JsonString.cs

Key being that ((int)c).ToString("x4") works

**Comment by DaniilVeriga** [comment]
Thank you for the report. Could you, please, provide a test case to reproduce the problem?

**Comment by serprex** [comment]
Enquote("x0f")
